sylius_twig_hooks:
    hooks:
        'synolia.sylius_admin.maintenance':
            sidebar:
                template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@SyliusAdmin/shared/crud/common/content.html.twig'
                priority: 0

        'synolia.sylius_admin.maintenance.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
                priority: 400
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 300
            form:
                template: '@SynoliaSyliusMaintenancePlugin/admin/maintenance/content/form.html.twig'
                priority: 200
            footer:
                template: '@SyliusAdmin/shared/crud/common/content/footer.html.twig'
                priority: 100

        'synolia.sylius_admin.maintenance.content.header':
            breadcrumbs:
                template: '@SynoliaSyliusMaintenancePlugin/admin/maintenance/content/header/breadcrumbs.html.twig'
                priority: 100
            title_block:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block.html.twig'
                priority: 0

        'synolia.sylius_admin.maintenance.content.header.title_block':
            title:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block/title.html.twig'
                configuration:
                    title: 'maintenance.ui.title'
                priority: 100
            actions:
                template: '@SyliusAdmin/shared/crud/update/content/header/title_block/actions.html.twig'
                priority: 0

        'synolia.sylius_admin.maintenance.content.header.title_block.actions':
            cancel:
                template: '@SynoliaSyliusMaintenancePlugin/admin/maintenance/content/header/title_block/actions/cancel.html.twig'
                priority: 100
            update:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block/actions/update.html.twig'
                priority: 0